# Generated by Django 5.0.6 on 2026-06-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="author",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="document",
            name="doc_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
