# Generated by Django 5.0.6 on 2026-06-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_document_author_document_doc_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
