# Generated by Django 5.0.6 on 2026-06-27 20:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_document_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="chunk",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="chunk_search_vector_gin"
            ),
        ),
    ]
