# Generated by Django 5.0.6 on 2026-06-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_chunk_search_vector_chunk_chunk_search_vector_gin"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="source_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
