# Generated by Django 5.0.6 on 2026-06-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_document_source_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="cost_usd",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="querylog",
            name="generation_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="querylog",
            name="retrieval_ms",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
